services:
   api:
      build: 
         context: ./node-app
         dockerfile: Dockerfile.prod
      image: node-api-img:1.0.0
      ports:
        - "5000:5000"
      environment:
         API_KEY: myapikeyvlaueesdfsdfsdf